# -*- coding: utf-8 -*-
"""Diet Type Recommendation System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZoDrPB_1XfjY9cwxGvAxFsG1CyQ8jeqb
"""

# AI Diet Recommendation System

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

# Sample dataset
data = {
    'Age': [18, 25, 30, 22, 40, 35, 28, 50],
    'Weight': [45, 70, 85, 55, 95, 68, 72, 88],
    'Height': [160, 170, 175, 165, 180, 172, 169, 178],
    'Goal': ['Gain', 'Maintain', 'Loss', 'Gain',
             'Loss', 'Maintain', 'Maintain', 'Loss'],
    'Diet': [
        'High Protein Diet',
        'Balanced Diet',
        'Low Carb Diet',
        'High Calorie Diet',
        'Keto Diet',
        'Balanced Diet',
        'Mediterranean Diet',
        'Low Fat Diet'
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Encode text values
le_goal = LabelEncoder()
le_diet = LabelEncoder()

df['Goal'] = le_goal.fit_transform(df['Goal'])
df['Diet'] = le_diet.fit_transform(df['Diet'])

# Features and target
X = df[['Age', 'Weight', 'Height', 'Goal']]
y = df['Diet']

# Train model
model = DecisionTreeClassifier()
model.fit(X, y)

# ---- User Input ----
print("=== AI Diet Recommendation System ===")

age = int(input("Enter Age: "))
weight = int(input("Enter Weight (kg): "))
height = int(input("Enter Height (cm): "))
goal = input("Enter Goal (Loss/Gain/Maintain): ")

# Encode goal
goal_encoded = le_goal.transform([goal])[0]

# Predict diet
prediction = model.predict([[age, weight, height, goal_encoded]])

# Decode output
diet_result = le_diet.inverse_transform(prediction)

print("\nRecommended Diet Plan:")
print(diet_result[0])

